(function(){
'use strict';
if(window.__MGR_ADS_BOOTED)return;
window.__MGR_ADS_BOOTED=true;
var ROOT='/data/ads-config.json',mounted={};
function log(){try{console.debug.apply(console,['[MangaGoRaw ads]'].concat([].slice.call(arguments)))}catch(e){}}
function load(){return fetch(ROOT+'?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('Ads config HTTP '+r.status);return r.json()}).catch(function(e){console.warn('[MangaGoRaw ads] config unavailable',e);return {sections:[]}})}
function slot(section,where){var key=String(section.id||'')+'|'+where;if(mounted[key])return null;mounted[key]=1;var wrap=document.createElement('div');wrap.className='mgraw-ad-slot';wrap.setAttribute('data-ad-id',String(section.id||''));wrap.setAttribute('data-ad-placement',where);wrap.id='mgraw-ad-'+String(section.id||'').replace(/[^a-zA-Z0-9_-]/g,'-')+'-'+String(where).replace(/[^a-zA-Z0-9_-]/g,'-');wrap.style.cssText='display:flex;justify-content:center;align-items:center;width:100%;min-height:20px;margin:18px auto;overflow:visible;clear:both;position:relative;z-index:1;';return wrap}
function render(section,where,parent){var code=String(section.code||'').trim();if(!code)return;var el=slot(section,where);if(!el)return;parent(el);var frame=document.createElement('iframe');frame.className='mgraw-ad-frame';frame.title='Advertisement';frame.loading='eager';frame.setAttribute('scrolling','no');frame.setAttribute('frameborder','0');frame.style.cssText='display:block;width:100%;max-width:100%;min-height:110px;border:0;overflow:hidden;background:transparent;';frame.srcdoc='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;padding:0;background:transparent;overflow:hidden;width:100%;min-height:100px}body{display:flex;justify-content:center;align-items:flex-start}</style></head><body>'+code+'</body></html>';el.appendChild(frame);log('mounted',section.id,where)}
function mount(cfg){var sections=Array.isArray(cfg.sections)?cfg.sections.filter(function(s){return s&&s.enabled&&String(s.code||'').trim()}):[];if(!sections.length){log('no enabled sections');return}var chapter=location.pathname.indexOf('/chapter.html')===0,reader=chapter?document.querySelector('.reader'):null;if(chapter&&!reader)return;sections.forEach(function(s){var p=String(s.placement||'start').toLowerCase(),n=Math.max(1,parseInt(s.between,10)||1);if(chapter&&p==='between'){var pages=document.querySelector('.pages'),imgs=pages&&pages.querySelectorAll('img.page');if(!imgs||imgs.length<n)return;render(s,'between-'+n,function(el){imgs[n-1].insertAdjacentElement('afterend',el)});return}if(chapter&&(p==='start'||p==='end')){render(s,p,function(el){p==='start'?reader.insertBefore(el,reader.firstChild):reader.appendChild(el)});return}if(!chapter&&p==='between')return;var target=document.querySelector('main')||document.body;render(s,p,function(el){p==='start'?target.insertBefore(el,target.firstChild):target.appendChild(el)})})}
function boot(){log('boot',location.pathname);load().then(function(cfg){var tries=0,timer=setInterval(function(){mount(cfg);tries++;var chapter=location.pathname.indexOf('/chapter.html')===0,ready=!chapter||!!document.querySelector('.pages');if(ready||tries>=80)clearInterval(timer)},250)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
